export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';



export const FETCH_GET_ALL_ARTISTS = 'FETCH_GET_ALL_ARTISTS';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_GET_THIS_ARTIST_ALBUMS = 'FETCH_GET_THIS_ARTIST_ALBUMS';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_GET_THIS_ALBUM_TRACKS = 'FETCH_GET_THIS_ALBUM_TRACKS';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_POST_THIS_TRACK_INFO = 'FETCH_POST_THIS_TRACK_INFO';
export const FETCH_TRACK_SUCCESS = 'FETCH_TRACK_SUCCESS';
export const FETCH_GET_TRACKS_HISTORY = 'FETCH_GET_TRACKS_HISTORY';
export const FETCH_TRACKS_HISTORY_SUCCESS = 'FETCH_TRACKS_HISTORY_SUCCESS';